### ISSUE TITLE
Figure out how to better coordinate the grand vision for Astropy Learn resources

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#138]
E.g., here's a planning document from PyAstro17 which has good vision in it:
https://docs.google.com/document/d/1zuiFrLD6Zisjak7a1saQC8jPpuL7FU8UbjPJeRokN98/edit#

**Comment by kelle** [comment]
Here's a sheet to start indexing all the things:
https://docs.google.com/spreadsheets/d/1JmOF82Zmrs397wLwAmmL1rgDSsvP6Z4fLMr0hV5ZIb4/edit?usp=sharing

**Comment by emilurice** [comment]
I am working on this project with @kelle

**Comment by emilurice** [comment]
Grand vision: Learning Python needs to have an accessible set of on ramps to the Astropy highway, with clear & frequent signage, long merge lanes, safe & comfortable for new drivers, thoughtful infrastructure plans, pretty landscaping and safety barriers, awareness of other drivers, etc. 

NOT like a NYC/LA on ramp that requires prior knowledge of where you're going (and where everyone else is coming from) and confidence in driving skills, only there because of historical accidents.

**Comment by kelle** [comment]
- Emily made a Project to describe org chart of Learn Astropy materials: https://github.com/astropy/astropy-tutorials/projects/3
- Google sheet compiling existing content, possible content, and topic keywords:
https://docs.google.com/spreadsheets/d/1JmOF82Zmrs397wLwAmmL1rgDSsvP6Z4fLMr0hV5ZIb4/edit?usp=sharing

**Comment by pllim** [comment]
Re: Google sheet -- Would be nice to add an example of how user can edit a FITS table when it is read into `astropy.table.Table` and then write it back out to FITS via unified I/O. This was brought up by @saraogaz at some point.

**Comment by kelle** [comment]
This info is all now contained in the Project and the documents linked there.
