### ISSUE TITLE
Consider replacing deploy machinery with sphinx-gallery 

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#145]
We could use sphinx-gallery to build and display the notebooks, and just not use (or do use) the gallery index page.

**Comment by adrn** [comment]
cc @astrofrog

**Comment by eteq** [comment]
Some things that the current machinery has (or that we could relatively easily add) that I think is important:
* Build single notebooks without the whole gallery
* Be able to skip lines as "should fail" (@astrofrog said this is possible in the sphinx-gallery already?)
* Report back whether or not the builds actually failed as a simple status code for travis usage

We should ensure `sphinx-gallery` can do these things.  I think the answer is yes, so then 👍 but otherwise we need to know whether that's going to be easier than rolling our own.

Also, I think you can customize the "gallery" page, right? So then we should just make it our index page and we get all the thumbnails as part of the gallery!

**Comment by adrn** [comment]
Damn, I think I was confused - I guess sphinx-gallery only operates on .py files with their formatting structure (see discussion in sphinx-gallery/sphinx-gallery#245). So going from ipynb directly to sphinx-gallery is not currently possible...

**Comment by adrn** [comment]
Just to complete the thought: this means that to use the sphinx-gallery machinery, we'd either have to (1) move all tutorials to .py files (which can be downloaded as jupyter notebooks), or (2) add an intermediate build step using nbconvert to turn the notebooks into .py files, then run sphinx-gallery. Given that, I'm now somewhat negative on the idea of switching...

To answer your concerns RE: sphinx-gallery:
* It doesn't support building single notebooks, but why is that important?
* A concept of "should fail" (note that our current machinery *does not* - we just ignore exceptions, so we never actually know if anything is broken!)
* This is gotten for free because the builds go through sphinx, which fail if any warnings or exceptions occur

**Comment by adrn** [comment]
(Though, in principle we could post-process the HTML we generate to add these links using [the machinery from sphinx-gallery](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/docs_resolv.py))

**Comment by kelle** [comment]
In the .py files, what does the narrative look like? Does it need to be in rst? I like the idea of the tutorials being in .py and notebooks simultaneously but I'm not excited about composing the narrative in rst.

**Comment by bsipocz** [comment]
> It doesn't support building single notebooks, but why is that important?

we said that one of our tes for the PR would be to check the modified tutorial works with the latest version of the dependencies, without checking the rest of them.

**Comment by eteq** [comment]
@adrn - 

> It doesn't support building single notebooks, but why is that important?

In addtion to @bsipocz 's item from https://github.com/astropy/astropy-tutorials/issues/145#issuecomment-331330518,  practice this is quite useful for review: you don't want to have to re-build *all* of the notebooks every time you need to inspect the one you're looking at.  It's not critical right now because they're all pretty fast, but if all goes well that won't last (c.f. the current sphinx build in astropy...)

> A concept of "should fail" (note that our current machinery does not ...

Agreed - my point above was that this is a necessity for the plan we outlined, so this is only a 👍  for sphinx-gallery *if* it's at least as, or easier as it will be for us to make that work with the current machinery.

@kelle re:

> In the .py files, what does the narrative look like?

The example @adrn linked is illustrative here.  The .py file is [here](https://github.com/astropy/astropy/blob/master/examples/coordinates/rv-to-gsr.py), and the rendered example is [here](http://docs.astropy.org/en/stable/generated/examples/coordinates/rv-to-gsr.html#sphx-glr-generated-examples-coordinates-rv-to-gsr-py)


IMHO the `.py` file approach is a lot harder for contributors, because the work flow is to either:
* Write the raw `.py` file, but then you then have to run a script to turn it into the pretty version rather than getting the quick feedback inherent in a notebook.  Also the narrative stuff is quite a bit harder . (This is *exactly* what the notebook was invented to make easier...)
* Write a notebook and then know you have to convert it into a `.py` file using a script or something

That said... @adrn, have you tried seeing if your "add an intermediate build step using nbconvert to turn the notebooks into .py files" actually works with the gallery?  That still may be simpler than our current scheme *if* we can get the "that line should fail" machinery to work somehow.

**Comment by eteq** [comment]
For anyone looking at this issue in the future:

After some (out-of-band) discussion on this topic we concluded the sphinx-gallery is not the way to go.  There was general agreement that the tutorials need to be written in notebooks.  So then we'd have to turn them into ``.py`` files that sphinx-gallery understands, and it might be a lot of work to make that function, especially given that notebooks use markdown and sphinx need rst.  

@adrn pointed out [nbsphinx](https://nbsphinx.readthedocs.io), though, which deals with all of the above issues.  So we are now thinking that's the better way to go.  That lets us keep a consolidated sphinx theme for both the astropy docs *and* the tutorials, while still letting us use the notebooks to produce the tutorials.  So I'm closing this issue in favor of another one to go the nbspinx route.
