### ISSUE TITLE
[Discussion] Set up 'v2' tutorial planning board?

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#196]
Inspired by the conversation on Slack, we have a few desired tutorials. Do we have enough to start a project board? Do we have critical mass to populate the project board?

* How to gauge code performance (e.g. `%%time`, `%%timeit`, and `%%lprun`)
* Installation, package management, and conda environments

Throw in your 2 cents.

**Comment by kelle** [comment]
I'm happy to use the Project Boards! 

The way we have been keeping track of new tutorial ideas is with the [content-new](https://github.com/astropy/astropy-tutorials/issues?q=is%3Aissue+is%3Aopen+label%3Acontent-new) label. But those can be tagged in a project board.

My thinking was that we'd incorporate performance learning opportunities into several tutorials rather than have a tutorial dedicated to it. But if someone has a vision for a tutorial dedicated to performance, that would be also be awesome.

**Comment by bsipocz** [comment]
> My thinking was that we'd incorporate performance learning opportunities into several tutorials rather than have a tutorial dedicated to it. But if someone has a vision for a tutorial dedicated to performance, that would be also be awesome.

From the sideline, I totally agree to incorporate performance tips into all tutorials, even if they are not highlighted as performance, as many of them are really just best practices (e.g. vectorize everything rather than loop over), and the more it's seen during the learning curve the more natural it become.

**Comment by eblur** [comment]
Project board started! https://github.com/astropy/astropy-tutorials/projects/4
