### ISSUE TITLE
Make a mockup of a new Astropy Learn website

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#200]
The vision is described in the "Landing Page" column of the [Learn Astropy Org Chart](https://github.com/astropy/astropy-tutorials/projects/3).  Before this can be developed, we need to have a mockup showing what it might look like. 
Functionality is demonstrated on [Zappos](Zappos.com) and [Royal Carribbean](https://secure.royalcaribbean.com/cruises/)

**Comment by littlewonder** [comment]
Hi! I'd like to work on this :-)

**Comment by littlewonder** [comment]
Hi @kelle I'd like to work on this :-) 
- I plan to make a low fidelity wireframe first, have everyone's suggestion and then make a high fidelity mockup of the discussed design.

Can you please assign this issue to me?

**Comment by kelle** [comment]
Hi @littlewonder. We'd love to see what you come with! And your plan sounds like a great one.

Since this is a possible Google Summer of Code project, there may be several people who want to make mockups. Therefore, I'd rather not assign it to anyone just yet.

**Comment by MananAgarwal** [comment]
Hi @kelle. I have prepared this draft of the mockup. I went through the [org chart](https://github.com/astropy/astropy-tutorials/projects/3) and tried to incorporate all the required features.

![mockup](https://user-images.githubusercontent.com/24625562/37255270-ddb3a7d4-256f-11e8-9bc6-23597448a121.jpg)
This is the landing page for learn.astropy with a dynamic search feature.

Below the search bar are placards which inform the user about the different types of study material. They double as a link to the list with all the material of that type. So if a user clicks a (say Tutorials) placard he/she will be redirected to learn.astropy.org/tutorials which will have all the tutorials.

The search results are also shown on placards. These placards have the title and a short description of the tutorial/guide/doc. The colored strip on the left corresponds to the type of study material. So a placard to red strip means it's a Tutorial and a placard with yellow strip means its a Documentation

Filters/categories are places on the left.

Looking forward to the community's suggestions.
Also in case of a query should I ask them here or is there an IRC channel?

**Comment by kelle** [comment]
Wow Manan, that looks great! Very well done! 

comments:
 - add thumbnail images to the placards search results. 
- add other search categories (keywords, companion materials) as collapsible menus. 

Best place for discussions is on the Astropy slack. Please follow this link to join: http://joinslack.astropy.org/ In addition to #general, There are also #learn and #gsoc channels you may be interested in. 

Thanks again for this great work!

**Comment by littlewonder** [comment]
Hey @kelle Sorry for getting on this late, was caught up in a hackathon! 
I have come up with this:
## Main Website Landing Page:
![Landing Page](https://i.imgur.com/TWPPD4X.jpg)

I tried to incorporate all the elements of org chart with simple illustrations. Not so sure about the background of the search box, I was thinking maybe we can try implementing a minimal CSS Animation of outer space or something, that can be changed. 

## Search Result Page:
![Search Page](https://i.imgur.com/kW7l5SQ.jpg)

You can search by filters using 'Search Everywhere' input box by narrowing down your search to either of Tutorials/Guide/Documentation/Examples. I have incorporated all the search categories on the left as collapsible just as you suggest. For colour coding rather than giving a solid fill border/ colour to the card, I gave it a label. Simple and Minimal.

I used this **colour palette** as a reference (Took care of branding, the colour code and fonts are same as Astropy home page).
![Palette](https://i.imgur.com/MIRJfLB.png)

Do let me know your thoughts and we can work on to improve this :-)

**Comment by kelle** [comment]
Hey @littlewonder - these two pages look really good!  I see that you've gotten some comments already on Slack and I agree with those.
On the search page, I really like dropdown and search options on each category. But I think we don't need three overall search boxes. I think we should just have one and there should not be a search bar in the common header.

**Comment by littlewonder** [comment]
@kelle **Update**
- Made the Faces more diverse
- Removed the search bar from the header
- The Second search bar on the search bar is to limit your results to, say, examples or guides. There's only one overall search.

## Landing Page
![](https://i.imgur.com/sOy7YuL.jpg)

## Search Page
![](https://i.imgur.com/p2EuiV0.png)

Have posted the designs in #learn on Slack Channel, hoping to get some more feedback :-)

**Comment by kelle** [comment]
@littlewonder @MananAgarwal These mockups are great starts! The next step is implementation. Please let us know how you think the dynamic search might be implemented in #203.

**Comment by kelle** [comment]
Thank you for your well thought out proposals! Now that they are in, I'm gonna close this issue.

**Comment by emilurice** [comment]
I want to make sure the red color doesn't read as "danger/warning/stress" red, especially given that the Tutorials should be the most accessible of the products. This might require adjusting the red in the astropy logo as well...
