### ISSUE TITLE
Learn.Astropy banner needs to redirect to home page (not Astropy.org)

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#307]
Right now there is no link back to the Learn Astropy homepage, after navigating to other parts of the Learn Astropy website. Clicking on the Learn Astropy banner sends us to astropy.org; it needs to be adjusted to send us back to learn.astropy.org

@eteq

**Comment by adrn** [comment]
For context: it looks like learn.astropy.org *redirects* to the gh-pages url astropy.org/astropy-tutorials, but I think we want to set this up as a CNAME or whatever so that learn.astropy.org *is* the site.

**Comment by adrn** [comment]
(the banner is a link to the root `/`, so that will fix this issue)

**Comment by agarwalrounak** [comment]
I will work on this issue.

**Comment by kakirastern** [comment]
Hi @adrn , I think linking to root with `/` only re-directs from the logo to [http://www.astropy.org](http://www.astropy.org/), since Astropy Learn's "default" URL is now at [http://www.astropy.org/astropy-tutorials/](http://www.astropy.org/astropy-tutorials/ )... unless our Landing Page is parked at another URL with an Astropy Learn specific domain name. 

Are we going to switch to the URL [learn.astropy.org](learn.astropy.org) with no redirection soon?

**Comment by kakirastern** [comment]
Think this issue is related to Issue #316 ...

**Comment by agarwalrounak** [comment]
@kakirastern yes, the redirection issue is related to #316 
Also, the higher-priority for now was that clicking on the Learn Astropy banner should send us back to learn.astropy.org or http://www.astropy.org/astropy-tutorials/ for that matter

**Comment by kakirastern** [comment]
@agarwalrounak Yes, I understand... but if we will be changing the URL then redirecting to root would solve problem. That's what I was implying.

**Comment by kakirastern** [comment]
Think the PR #325 dealing with this Issue can also fix Issue #323... (Almost literally one-stone-two-birds.)

**Comment by kakirastern** [comment]
**Alternative solution**: Setting "http://learn.astropy.org/ as one of the `A Record`'s instead of a `CNAME` should fix the issue too...
