### ISSUE TITLE
keep keyword list long if hidden keyword is selected

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#382]
If a keyword is selected from the "more" list, it is hidden in subsequent pages. Please modify so that the list stays open when a keyword is selected from the hidden list.

**Comment by kakirastern** [comment]
I checked and the issue seems to have arisen from the webpage refreshing each time a keyword is selected from the side navbar, such that the "View More" list does not remain open after search results are displayed.

**Comment by kakirastern** [comment]
I think one way to tackle this problem is to upgrade our website with tools such as React JS that will allow us to render sphinx documentation, such as with the use of Gatsby: https://www.gatsbyjs.org/blog/2019-02-14-behind-the-scenes-q-and-a/#functional-questions-how-do-i-do-x-with-gatsby where it says: 

> Question: Gatsby transformers support Markdown and asciidoc. Possible support for Sphinx reStructuredText? Answer: Certainly! Gatsby is super pluggable, so whatever content you want to bring to Gatsby, just write a plugin! Check out Creating a Source Plugin.

**Comment by kakirastern** [comment]
Seems like the whole upgrade can be accomplished within a week as suggested here: https://medium.com/@mtiller/rendering-sphinx-documentation-with-react-95b785293a76
