### ISSUE TITLE
Tutorials not loading on learn.astropy.org

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#397]
It looks like the tutorials aren't being loaded properly:

![image](https://user-images.githubusercontent.com/583379/64024242-eb09ac00-cb07-11e9-8f94-70a447b71fa6.png)

This is on navigating to http://learn.astropy.org/tutorials.html with no filter applied. Note also the last tutorial card appears truncated.

Any ideas @MananAgarwal ?

**Comment by MananAgarwal** [comment]
This is really weird.
It shows a different number every time I reload. I got 3, 5 and 6 tutorials.

**Comment by MananAgarwal** [comment]
For me, it's working perfectly fine on Safari and Firefox.
Also, in incognito mode of Google Chrome.

**Comment by MananAgarwal** [comment]
It works in Google Chrome if you do a hard refresh (cmd + shift + R)

**Comment by adrn** [comment]
Weird - it must be something with the way Chrome caches? It does work for me with a hard refresh, but then if I do a normal refresh it is back to randomly showing random subsets of the tutorials... WTF?!?

**Comment by MananAgarwal** [comment]
Yes, I am getting the same behaviour.

**Comment by MananAgarwal** [comment]
The tutorial card is getting truncated because something (definately not something in our code) is updating the style attribute of the last card.

<img width="1621" alt="Screenshot 2019-08-31 at 3 07 09 AM" src="https://user-images.githubusercontent.com/24625562/64052592-af6cf180-cb9c-11e9-9062-b927e3d7b5cb.png">

**Comment by kakirastern** [comment]
It appears that if you search for tutorials using the "Search for a filter" field for some key words that are not ones having been standardised in the database, the tutorial cards are not truncated, like the following using "scipy.integrate" as the search term:

<img width="1195" alt="Screenshot 2019-09-10 00 27 38" src="https://user-images.githubusercontent.com/26264600/64548805-f8256700-d361-11e9-9ed0-08062f8909c7.png">

And there is the case with "data cubes": If you use the "Search for a filter" field the tutorial cards returned are fine, and it appears to to fine too if you choose the same option from the form below under the "Task" category... 

So compare Case 1 using "Search for a filter":

<img width="1195" alt="Screenshot 2019-09-10 00 32 15" src="https://user-images.githubusercontent.com/26264600/64549084-8bf73300-d362-11e9-95c5-f9169b014ff9.png">

with Case 2 by checking the "data cubes" box under "Task" category:

<img width="1176" alt="Screenshot 2019-09-10 00 34 20" src="https://user-images.githubusercontent.com/26264600/64549235-e3959e80-d362-11e9-8828-02385aa239c4.png">

**Comment by kakirastern** [comment]
Could it have to do with some JavaScript `async` or even some `timeout` behaviour in the theme? The latter could explain why for some keyword searches the number of tutorial cards turned up at different times are different...

**Comment by MananAgarwal** [comment]
What I think is happening is that when the browser is loading the content from cache "$(window).on('load',..." is called prematurely. There is a difference of about 200-500ms between Load time and Finish time of the page. I have updated the code to wait for 1 sec (we can reduce this in future) before counting the number of tutorials results. Since this is an asynchronous call, the delay is only in displaying the number of tutorials found and not the tutorials cards itself, so the user experience is not affected.

**Comment by MananAgarwal** [comment]
It was working on a hard refresh because then the Load time and Finish time are the same.
